name: Build Packages

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      package_version:
        description: The version of the package built by make
        value: ${{ jobs.build.outputs.package_version }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.extract_package_version.outputs.package_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Europe/Bucharest
          # Verify the timezone was set
          date

      - name: Get Current Tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          if [ "$TAG_NAME" == "refs/heads/main" ]; then
            TAG_NAME="0.0.0"
          fi
          echo "Current Tag: $TAG_NAME"
          # Export the tag name as a GitHub Actions environment variable
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Build Packages
        run: make docker-artifact-build

      - name: Extract Package Version
        id: extract_package_version
        run: |
          PACKAGE_FILE=$(ls pkgs/unraid.network.disk.unlock-*.txz)
          PACKAGE_VERSION=$(echo $PACKAGE_FILE | grep -Po '(\d{4}\.\d{2}\.\d{2})-[^-]+-(\d+)(?=_)' | sed -E 's|-[^-]+-|-|' )
          echo "Package Version: $PACKAGE_VERSION"
          # Export the package version as a step outout value
          echo "package_version=${PACKAGE_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: slackbuild-pkgs
          path: pkgs/*
