name: Build Packages

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Current Tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Current Tag: $TAG_NAME"
          # Export the tag name as a GitHub Actions environment variable
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Build Packages
        run: make docker-artifact-build DOCKER_IMAGE_VERSION="$TAG_NAME"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: slackbuild-pkgs
          path: pkgs/*
