name: Create Release

on:

  workflow_dispatch:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]'

jobs:

  build:
    uses: ./.github/workflows/build.yml

  create_release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Packages from build step
      uses: actions/download-artifact@v4
      with:
        name: slackbuild-pkgs
        path: pkgs/

    - name: Debug Inputs
      run: |
        echo "Received package_version=${{ needs.build.outputs.package_version }}"
      shell: bash

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ needs.build.outputs.package_version }}
        name: v${{ needs.build.outputs.package_version }}
        draft: true
        files: pkgs/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}